In [37]:
os.getcwd()
sys.path.append('../')
from  mst import Graph

In [38]:
import os
import sys
import numpy as np
import heapq
from typing import Union
import networkx as nx

In [39]:
import numpy as np

# Create a 2D numpy array to represent the adjacency matrix of the graph
adjacency_mat = np.array([[0, 2, 0, 6, 0], [2, 0, 3, 8, 5], [0, 3, 0, 0, 7], [6, 8, 0, 0, 9], [0, 5, 7, 9, 0]])

# Create an instance of the Graph class with the adjacency matrix
graph = Graph(adjacency_mat)

# Construct the minimum spanning tree of the graph
graph.construct_mst()

# Access the minimum spanning tree
print(graph.mst)
# Output:
# [[0. 2. 0. 0. 0.]
#  [2. 0. 3. 0. 0.]
#  [0. 3. 0. 0. 0.]
#  [0. 0. 0. 0. 9.]
#  [0. 0. 0. 9. 0.]]

[[0. 2. 0. 6. 0.]
 [2. 0. 3. 0. 5.]
 [0. 3. 0. 0. 0.]
 [6. 0. 0. 0. 0.]
 [0. 5. 0. 0. 0.]]
